### ISSUE TITLE
Add the rewards calculation and visualization

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/rewards-view#5]
## Description
Currently only the challenges status is displayed. We should add also the amount of DSM that each user has gained. 

The rewards should be computed based on how much each single challenge is worth. The values are the following. 

### Primer Phase 1
- 200 DSM per each accepted referral
- 20 DSM for the post
- 10 DSM for the like 
- 50 DSM if someone referred the user and the referral was accepted

### Primer Phase 2 
- 30 DSM for the reaction
- 300 DSM for the validator creation

### Primer Phase 3 
- 100 DSM for the poll
- 10 DSM for the poll answer
- 50 DSM for the multimedia post

Plus, the following rewards should be given based on the number of blocks validated: 

| Pre-commits signed | Tokens rewarded | 
| :----------------: | :-------------: |
| 1 | 1 |
| 4 | 2 |
| 18 | 3 |
| 78 | 7 |
| 331 | 12 |
| 1,416 | 21 |
| 6,044 | 40 |
| 25,796 | 73 |
| 110,097 | 135 |
| 469,894 | 250 |

### Primer Phase 4 
- 50 DSM for the account
- 50 DSM for the reaction
- 50 DSM for the update 

Plus, the following rewards should be given based on the number of blocks validated: 

| Pre-commits signed | Tokens rewarded | 
| :----------------: | :-------------: |
| 345,600 | 1,500 |
| 353,480 | 1,750 |
| 361,540 | 2,040 |
| 369,790 | 2,380 |
| 378,220 | 2,780 |
| 386,850 | 3,240 |
| 395,670 | 3,780 |
| 404,690 | 4,410 |
| 413,920 | 5,140 |
| 423,360 | 6,000 |

### Primer Phase 5 
- 25 DSM for the hashtag
- 50 DSM for the account 
- 25 DSM for the report
- 50 DSM for the tag 
- 50 DSM for the update 

Plus, the following rewards should be given based on the number of blocks validated: 

| Pre-commits signed | Tokens rewarded | 
| :----------------: | :-------------: |
| 476,534 | 1,500 |
| 488,497 | 1,750 |
| 500,760 | 2,040 |
| 513,331 | 2,380 |
| 526,217 | 2,780 |
| 539,427 | 3,240 |
| 552,969 | 3,780 |
| 566,851 | 4,410 |
| 581,081 | 5,140 |
| 595,668 | 6,000 |   

### Validating summer
Each validator that has signed at least 462,631 precommits should receive 6,000 DSM as a reward.

**Comment by ryuash** [comment]
Is this frontend calculation or is there a gql aggregation

**Comment by RiccardoM** [comment]
> Is this frontend calculation or is there a gql aggregation

It's all frontend calculation for now
